version: "3"

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/docs/Dockerfile.dev

    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/app

    networks:
      - app_network

networks:
  app_network:
    external: true