# Base image
FROM node:18-alpine AS base
RUN apk add --no-cache libc6-compat bash

# Development stage
FROM base AS dev
WORKDIR /app

# Install pnpm globally
RUN npm install -g pnpm

# Set up pnpm global bin directory
ENV PNPM_HOME=/root/.local/share/pnpm
ENV PATH=$PNPM_HOME:$PATH

# Install turbo globally
RUN pnpm add -g turbo

# Copy only necessary files and directories to the container
COPY pnpm-workspace.yaml turbo.json package.json pnpm-lock.yaml ./
COPY apps/docs /app/apps/docs
COPY packages /app/packages

# Install dependencies
RUN pnpm install

# Expose the port that the Next.js app will run on
EXPOSE 3000

# Run the Next.js development server
CMD [ "pnpm", "turbo", "dev", "--filter=docs" ]