name = "nextjs-ssr-app"
type = "javascript"  # Set the type for serverless JavaScript

# Point to the main SSR server file in standalone output
main = ".next/standalone/server.js"

[site]
bucket = ".next/static"
